AWSTemplateFormatVersion: 2010-09-09
Transform: S3Objects
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3Bucket
                - /*
      Bucket: !Ref S3Bucket
  S3Object:
    Type: 'AWS::S3::Object'
    Properties:
      Target:
        Bucket: !Ref S3Bucket
        Key: index.html
        ContentType: text/html
      Body: !Sub |
        <html>
            <head>
                <title>Static Website with CloudFormation</title>
            </head>
            <body>
                <b>Hello world from CloudFormation, served by S3</b>
            </body>
        </html>

Outputs:
  WebsiteURL:
    Value: !GetAtt 
      - S3Bucket
      - WebsiteURL
    Description: URL for website hosted on S3
